In [22]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import scale
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

In [2]:
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = Perceptron()
clf.fit(X, y)
predictions = clf.predict(X)

/Users/antonio/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [3]:
print(predictions)

[0 0 0]


In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = np.array([[100.0, 2.0], [50.0, 4.0], [70.0, 6.0]])
X_test = np.array([[90.0, 1], [40.0, 3], [60.0, 4]])
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
print(X_train_scaled)
print(X_test_scaled)

[[ 1.29777137 -1.22474487]
 [-1.13554995  0.        ]
 [-0.16222142  1.22474487]]
[[ 0.81110711 -1.83711731]
 [-1.62221421 -0.61237244]
 [-0.64888568  0.        ]]


In [17]:
# начнем
df = pd.read_csv("perceptron-train.csv", names=["target", "f1", "f2"])
y_train = df.target
X_train = df.drop("target", axis=1)

df = pd.read_csv("perceptron-test.csv", names=["target", "f1", "f2"])
y_test = df.target
X_test = df.drop("target", axis=1)

In [21]:
clf = Perceptron(random_state=241)
clf.fit(X_train, y_train)


/Users/antonio/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Perceptron(alpha=0.0001, class_weight=None, eta0=1.0, fit_intercept=True,
      max_iter=5, n_iter=None, n_jobs=1, penalty=None, random_state=241,
      shuffle=True, tol=None, verbose=0, warm_start=False)

In [26]:
#print(clf.predict(X_test))
acc1 = accuracy_score(y_test, clf.predict(X_test))
print(acc1)

0.655


In [27]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [30]:
clf_scaled = Perceptron(random_state=241)
clf_scaled.fit(X_train_scaled, y_train)

/Users/antonio/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Perceptron(alpha=0.0001, class_weight=None, eta0=1.0, fit_intercept=True,
      max_iter=5, n_iter=None, n_jobs=1, penalty=None, random_state=241,
      shuffle=True, tol=None, verbose=0, warm_start=False)

In [31]:
acc2 = accuracy_score(y_test, clf_scaled.predict(X_test_scaled))
print(acc2)

0.845


In [32]:
print(acc2 - acc1)
with open("perceptron_res.txt", "w") as f:
    print("%.3f" % (acc2 - acc1), file=f, sep='')


0.19
